apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        prometheus.io/probe: "true"
      name: $NAME
      namespace: $NAMESPACE
    spec:
      ports:
        - name: http
          port: $PORT
          protocol: TCP
          targetPort: $PORT
      selector:
        k8s-app: "$NAME"
      sessionAffinity: None
      type: ClusterIP

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        k8s-app: "$NAME"
      name: $NAME
      namespace: $NAMESPACE
    spec:
      replicas: 1
      selector:
        matchLabels:
          k8s-app: "$NAME"
      template:
        metadata:
          annotations:
            fvg.app: $NAME
            fvg.description: Back office design system
            fvg.domain: $NAMESPACE
            fvg.role: ui
          labels:
            k8s-app: "$NAME"
        spec:
          containers:
            - name: $NAME
              image: $IMG_NAME
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: $PORT
                  name: http
                  protocol: TCP
              resources:
                limits:
                  cpu: $RESOURCES_LIMITS_CPU
                  memory: $RESOURCES_LIMITS_MEMORY
                requests:
                  cpu: $RESOURCES_REQUESTS_CPU
                  memory: $RESOURCES_REQUESTS_MEMORY
          dnsPolicy: ClusterFirst
          imagePullSecrets:
            - name: $IMAGE_PULL_SECRETS
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30

  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: $NAME
      namespace: $NAMESPACE
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
    spec:
      rules:
        - host: $INGRESS_HOST
          http:
            paths:
              - path: /
                backend:
                  serviceName: $NAME
                  servicePort: http
      tls:
        - hosts:
            - $INGRESS_HOST
          secretName: $TLS_SECRET_NAME
